#!/bin/bash

echo "To push the backend to GitHub, you need to create a new repository."
echo "Please follow these steps:"
echo ""
echo "1. Go to https://github.com/new"
echo "2. Create a new repository with the name 'asistenguru-backend'"
echo "3. Do NOT initialize with a README, .gitignore, or license"
echo "4. After creating the repository, run the following commands:"
echo ""
echo "   cd /home/eki/AsistenGuruV3/backend"
echo "   git remote add origin https://github.com/eki220694/asistenguru-backend.git"
echo "   git push -u origin main"
echo ""
echo "Alternatively, if you want to add the backend as a subdirectory to the existing AsistenGuruV3 repository:"
echo ""
echo "   cd /home/eki/AsistenGuruV3/asistenguruv3"
echo "   mkdir backend"
echo "   cp -r /home/eki/AsistenGuruV3/backend/* backend/"
echo "   git add backend/"
echo "   git commit -m \"Add backend to the repository\""
echo "   git push origin main"
echo ""